<%@ Language=VBScript %>
<!--#include file="..\lib\common.inc"-->
<HTML>
<HEAD>
<link rel="stylesheet" type="text/css" href="..\FNSDESIGN.css">
</HEAD>
<BODY  leftmargin=0 topmargin=0>
<FIELDSET STYLE="BACKGROUND:SILVER;WIDTH='100%'">
<TABLE WIDTH="100%" >
<TR BGCOLOR=SILVER>
<TD CLASS=LABEL>
<FONT SIZE=2>Node Details</FONT>
</TD>
<TD STYLE="WIDTH:10" OnCLick="Window.History.Back(1)" CLASS=LABELHEADER>U</TD>
<TD STYLE="WIDTH:10" OnCLick="Window.History.Back(1)" CLASS=LABELHEADER>S</TD>
</TR>
</TABLE>
</FIELDSET>

<FIELDSET STYLE="BACKGROUND:SILVER">
<TABLE>
<TR>
<TD CLASS=LABEL>Name:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="NAME" SIZE=95></TD>
<TD></TD>
</TR>
</TABLE>
<TABLE>
<TR>
<TD CLASS=LABEL>Address 1:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="ADDRESS2" SIZE=45></TD>
<TD CLASS=LABEL>Address 2:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="ADDRESS1" SIZE=45></TD>
</TR>
</TABLE>
<TABLE>
<TR>
<TD CLASS=LABEL>City:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="CITY" SIZE=50></TD>
<TD CLASS=LABEL>State:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="STATE" SIZE=2></TD>
<TD CLASS=LABEL>Zip:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="ZIP" SIZE=10></TD>
</TR>
</TABLE>
<TABLE>
<TR>
<TD CLASS=LABEL>Phone:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="PHONE" SIZE=25></TD>
<TD CLASS=LABEL>Fax:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="FAX" SIZE=25></TD>
</TR>
</TABLE>
<TABLE>
<TR>
<TD CLASS=LABEL>Nature of Business:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="NATURE_OF_BUSINESS" SIZE=25></TD>
<TD CLASS=LABEL>Node Level:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="NODE_LEVEL" SIZE=25></TD>
<TD CLASS=LABEL>Escalation Call:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="ESALATION_CALL" SIZE=25></TD>
</TR>
</TABLE>
<TABLE>
<TR>
<TD CLASS=LABEL>Upload Key:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="UPLOAD_KEY" SIZE=25></TD>
<TD CLASS=LABEL>Active Status:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="ACTIVE_STATUS" SIZE=25></TD>
<TD CLASS=LABEL>Policy Search ID:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="POLICY_SEARCH_ID" SIZE=25></TD>
</TR>
</TABLE>
<TABLE>
<TR>
<TD CLASS=LABEL>Status Date:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="STATUS_DATE" SIZE=25></TD>
<TD CLASS=LABEL>Client Node ID:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="CLIENT_NODE_ID" SIZE=25></TD>
<TD CLASS=LABEL>Parent Node ID:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="PARENT_NODE_ID" SIZE=25></TD>
</TR>
<TR>
<TD CLASS=LABEL>FNS Client Code:<BR><INPUT TYPE=TEXT CLASS=LABEL NAME="FNS_CLIENT_CODE" SIZE=3></TD>
<TD CLASS=LABEL><NOBR><INPUT TYPE=CHECKBOX CLASS=LABEL NAME="AUTO_ESCALATE" SIZE=25>Auto Escalate?</TD>
</TR>
</TABLE>
</FIELDSET>
<BR><BR>
<CENTER>
<BUTTON CLASS=STDBUTTON>Save</BUTTON>&nbsp;
<BUTTON CLASS=STDBUTTON>Cancel</BUTTON>
</CENTER>
</BODY>
</HTML>
