<!--#include file="..\lib\common.inc"-->
<%
If Len(Request.QueryString("OPID")) < 1 OR IsNumeric(Request.QueryString("OPID")) = False Then
	Session("ErrorMessage") = "On page " &  Request.ServerVariables("SCRIPT_NAME") & " QueryString OPID was Null or Not Numeric"
	Response.Redirect "..\directerror.asp"
End If
	Set Conn = Server.CreateObject("ADODB.Connection")
	ConnectionString = CONNECT_STRING
	Conn.Open ConnectionString
	SQLST = "SELECT OUTPUT_PAGE.OUTPUT_PAGE_ID, OUTPUT_FIELD.NAME, OUTPUT_PAGE.PAGE_NUMBER, OUTPUT_PAGE.OUTPUT_TRAY, OUTPUT_PAGE.BACKGROUND_BMP, OUTPUT_FIELD.XPOS, OUTPUT_FIELD.YPOS,"
	SQLST = SQLST & "OUTPUT_FIELD.WIDTH, OUTPUT_FIELD.HEIGHT, OUTPUT_FIELD.BMP, OUTPUT_FIELD.FONT_NAME, OUTPUT_FIELD.OUTPUT_FLD_ID, OUTPUT_FIELD.FONT_SIZE, OUTPUT_FIELD.BOLD_FLG, OUTPUT_FIELD.ITALIC_FLG, 	OUTPUT_FIELD.UNDERLINE_FLG,"
	SQLST = SQLST & "OUTPUT_FIELD.MAPPING, OUTPUT_FIELD.STRIKEOUT_FLG, OUTPUT_FIELD.MULTILINE_FLG FROM OUTPUT_PAGE, OUTPUT_FIELD WHERE OUTPUT_PAGE.OUTPUT_PAGE_ID = " & Request.QueryString("OPID") & " AND OUTPUT_PAGE.OUTPUT_PAGE_ID = OUTPUT_FIELD.OUTPUT_PAGE_ID ORDER BY OUTPUT_FIELD.NAME" 
	Set RS = Conn.Execute(SQLST)
%>
<HTML>
<HEAD>
<link rel="stylesheet" type="text/css" href="..\FNSDESIGN.css">
<STYLE>
.LABELLIST
{
FONT-FAMILY:VERDANA;
FONT-SIZE:12;
COLOR:WHITE;
BACKGROUND-COLOR:#006699;
}
.LABELDATA
{
FONT-FAMILY:VERDANA;
FONT-SIZE:10;
}
</STYLE>
</HEAD>
<BODY BGCOLOR='<%=BODYBGCOLOR%>' >
<TABLE WIDTH="100%" CELLPADDING="0" CELLSPACING="0">
<TR><TD colspan=2 HEIGHT=4></TD></TR>
<TR><TD CLASS=GrpLabel WIDTH="134" HEIGHT=10>&nbsp&#187 Output Field Listing</TD>
<TD HEIGHT=5 ALIGN=LEFT>
<TABLE CELLPADDING="0" CELLSPACING="0" HEIGHT=100%>
<TR><TD WIDTH=3 HEIGHT=4></TD><TD WIDTH=300 HEIGHT=4></TD></TR>
<TR><TD CLASS=GrpLabelDrk WIDTH=3 HEIGHT=8 VALIGN=BOTTOM ALIGN=LEFT></TD>
<TD WIDTH=300 HEIGHT=8></TD></TR>
</TABLE></TD></TR>
<TR><TD CLASS=GrpLabelLine colspan=2 HEIGHT=1></TD></TR>
<TR><TD colspan=2 HEIGHT=1></TD></TR>
</TABLE>

<TABLE WIDTH="100%" CELLSPACING=0 CELLPADDING=5 >
<TR>
<TD CLASS=LABELLIST >Name</TD>
<TD CLASS=LABELLIST >XPos</TD>
<TD CLASS=LABELLIST >Ypos</TD>
<TD CLASS=LABELLIST >Width</TD>
<TD CLASS=LABELLIST >Height</TD>
<TD CLASS=LABELLIST >Font</TD>
<TD CLASS=LABELLIST ><NOBR>Font Size</TD>
<TD CLASS=LABELLIST WIDTH=200>Mapping</TD>
</TR>
<% 
If Not RS.EOF or Not isnull(RS) Then
	Do While Not RS.EOF %>
<TR>
<TD CLASS=LABELDATA><%= RS("NAME") %></TD>
<TD CLASS=LABELDATA><%= RS("XPOS") %></TD>
<TD CLASS=LABELDATA><%= RS("YPOS") %></TD>
<TD CLASS=LABELDATA><%= RS("WIDTH") %></TD>
<TD CLASS=LABELDATA><%= RS("HEIGHT") %></TD>
<TD CLASS=LABELDATA><%= RS("FONT_NAME") %></TD>
<TD CLASS=LABELDATA><%= RS("FONT_SIZE") %></TD>
</TR>
<TR>
<TD colspan=12 CLASS=LABELDATA><%= RS("MAPPING") %></TD>
</TR>
<TR>
<TR><TD CLASS=GrpLabelLine colspan=12 HEIGHT=1></TD></TR>
<TR><TD colspan=12 HEIGHT=1></TD></TR>
<% 
	RS.MoveNext
	Loop
	RS.Close
End If
%>
</TABLE>
</BODY>
</HTML>