<%
 
const FMTName = "Fremont Compensation"
const FMTNo = 75

const FREName = "Fremont CIP"
const FRENo = 71

const MARName = "Marriott"
const MARNo = 72

const GBSName = "Gallagher Basset Services, Inc"
const GBSNo = 46

const AIGName = "American International Group"
const AIGNo = 62

const ULIName = "ULICO"
const ULINo = 76

const TIGName = "TIG Insurance"
const TIGNo = 59

const MCDName = "McDonalds"
const MCDNo = 73

const KMPName = "Kemper"
const KMPNo = 31

const KMPCATName = "Kemper-CAT"
const KMPCATNo = 31

const CCEName = "Claim Capture Express"
const CCENo = 11

const AFFName = "Affirmative Insurance Services"
const AFFNo = 21675233

const AFFMName = "Affirmative Insurance Services"
const AFFMNo = 550

const LACName = "Los Angeles County"
const LACNo = 52

const WIGName = "Workmens Auto Insurance"
const WIGNo = 104

const MGCNameReg = "Managed Comp - Regular Callflow"
const MGCNoReg = 103

const MGCNameIRC = "Managed Comp - IRC Callflow"
const MGCNoIRC = 103

const PCNName = "Princeton Insurance"
const PCNNo = 12

const AIMName = "AIM"
const AIMNo = 13

const NBICName = "NBIC"
const NBICNo = 444


const ARGName = "Argonaut Insurance"
const ARGNo = 14

const ONBName = "One Beacon Insurance"
const ONBNo = 20

const CSGNameCall = "CISG ClaimCapture Call Center Intake"
const CSGNoCall = 15

const CSGNameOnline = "CISG ClaimCapture Online Reporting"
const CSGNoOnline = 15

const CSGNameSummary = "CISG Summary Billing"
const CSGNoSummary = 15

const FGName = "Frank Gates"
const FGNo = 105

const STAName = "State Auto Insurance"
const STANo = 30

const RDCName = "Certified Restoration"
const RDCNo = 25

const AIKName = "AIK"
const AIKNo = 16

const WMAName = "WASTE MANAGEMENT INC"
const WMANo = 12159325

const SHPRName = "Sunstone Hotel Property"
const SHPRNo = 14504629

const CVGName = "COMMONWEALTH OF VIRGINIA"
const CVGNo = 12801314

const CSAAName = "CSAA"
const CSAANo = 102

const AAAName = "AAA Insurance"
const AAANo = 111

const CIRName = "Connecticut Interlocal RMA"
const CIRNo = 123

const CRWNameASP = "Crawford ASP Claims"
const CRWNoASP = 81
const CRWNameFNS = "Crawford Internet/Overflow Report"
const CRWNoFNS = 81

const MERName = "Merastar"
const MERNo = 106

const BRKName = "Berkley Risk"
const BRKNo = 88

const MTSName = "Mitsui"
const MTSNo = 66

const AMCName = "AM COMP"
const AMCNo = 222

const PMCOName = "PEMCO"
const PMCONo = 615

const ESISName = "ESIS"
const ESISNo = 202

const SENName = "Sentry"
const SENNo = 200

const SEAName = "SeaBright"
const SEANo = 22

const ACEName = "ACE"
const ACENo = 206

const EMCName = "EMC"
const EMCNo = 67

const NTWName = "NTW"
const NTWNo = 255

const CNLName = "Canal"
const CNLNo = 150

const CNLNameNew= "Canal3-in-1"
const CNLNewNo= 150

const CHBName = "CHB"
const CHBNo = 157

const RTWName = "RTW"
const RTWNo = 325

const ALMName = "ALM"
const ALMNo = 650

const HMLName = "Harford Mutual"
const HMLNo = 387

const SELName = "Selective"
const SELNo = 277

const SRSName = "SRS"
const SRSNo =600

const UNIName = "Unisource"
const UNINo = 620

const EVRName = "Everest National"
const EVRNo = 155

const TGCName = "Tower Group Of Companies"
const TGCNo = 190

const TGCNameASP = "TOWER GROUP COMPANIES"
const TGCNoASP = 800

const SAFName = "Safety Insurance"
const SAFNo = 228

const ANIName = "Alaska National"
const ANINo = 152

const AMEName = "AME Ameriprise"
const AMENo = 1000
%>