<SCRIPT LANGUAGE="JavaScript" FOR="BillingBtnControl" EVENT="onscriptletevent (event, obj)">
   switch (event)
	{
		case "EDITBUTTONCLICK":
			window.location.href = "about:blank";
			break;

		case "NEWBUTTONCLICK":
			window.location.href = "about:blank";
			break;

		case "COPYBUTTONCLICK":
			window.location.href = "about:blank";
			break;

		case "PASTEBUTTONCLICK":
			window.location.href = "about:blank";
			break;

		case "SEARCHBUTTONCLICK":
			window.location.href = "about:blank";
			break;

		case "REMOVEBUTTONCLICK":
			window.location.href = "about:blank";

			break;

		default:
			break;
	}
   
</SCRIPT>