<%= "<OPTION VALUE='AA'>AA<OPTION VALUE='AB'>AB<OPTION VALUE='AE'>AE" %>
<%= "<OPTION VALUE='AK'>AK" %>
<%= "<OPTION VALUE='AL'>AL<OPTION VALUE='AP'>AP<OPTION VALUE='AR'>AR" %>
<%= "<OPTION VALUE='AS'>AS<OPTION VALUE='AZ'>AZ<OPTION VALUE='BC'>BC" %>
<%= "<OPTION VALUE='CA'>CA" %>
<%= "<OPTION VALUE='CO'>CO<OPTION VALUE='CT'>CT<OPTION VALUE='DC'>DC" %>
<%= "<OPTION VALUE='DE'>DE<OPTION VALUE='FL'>FL<OPTION VALUE='FM'>FM" %>
<%= "<OPTION VALUE='GA'>GA<OPTION VALUE='GU'>GU<OPTION VALUE='HI'>HI" %>
<%= "<OPTION VALUE='IA'>IA<OPTION VALUE='ID'>ID<OPTION VALUE='IL'>IL" %>
<%= "<OPTION VALUE='IN'>IN<OPTION VALUE='KS'>KS<OPTION VALUE='KY'>KY" %>
<%= "<OPTION VALUE='LA'>LA<OPTION VALUE='MA'>MA<OPTION VALUE='MB'>MB" %>
<%= "<OPTION VALUE='MD'>MD" %>
<%= "<OPTION VALUE='ME'>ME<OPTION VALUE='MH'>MH<OPTION VALUE='MI'>MI" %>
<%= "<OPTION VALUE='MN'>MN<OPTION VALUE='MO'>MO<OPTION VALUE='MP'>MP" %>
<%= "<OPTION VALUE='MS'>MS<OPTION VALUE='MT'>MT<OPTION VALUE='NB'>NB" %>
<%= "<OPTION VALUE='NC'>NC" %>
<%= "<OPTION VALUE='ND'>ND<OPTION VALUE='NE'>NE<OPTION VALUE='NH'>NH" %>
<%= "<OPTION VALUE='NJ'>NJ<OPTION VALUE='NL'>NL<OPTION VALUE='NM'>NM" %>
<%= "<OPTION VALUE='NS'>NS<OPTION VALUE='NT'>NT<OPTION VALUE='NU'>NU" %>
<%= "<OPTION VALUE='NV'>NV" %>
<%= "<OPTION VALUE='NY'>NY<OPTION VALUE='OH'>OH<OPTION VALUE='OK'>OK" %>
<%= "<OPTION VALUE='ON'>ON<OPTION VALUE='OR'>OR<OPTION VALUE='PA'>PA" %>
<%= "<OPTION VALUE='PE'>PE<OPTION VALUE='PR'>PR<OPTION VALUE='PW'>PW" %>
<%= "<OPTION VALUE='QC'>QC<OPTION VALUE='RI'>RI<OPTION VALUE='SC'>SC" %>
<%= "<OPTION VALUE='SD'>SD<OPTION VALUE='SK'>SK<OPTION VALUE='TN'>TN" %>
<%= "<OPTION VALUE='TX'>TX" %>
<%= "<OPTION VALUE='UT'>UT<OPTION VALUE='VA'>VA<OPTION VALUE='VI'>VI" %>
<%= "<OPTION VALUE='VT'>VT<OPTION VALUE='WA'>WA<OPTION VALUE='WI'>WI" %>
<%= "<OPTION VALUE='WV'>WV<OPTION VALUE='WY'>WY<OPTION VALUE='YT'>YT" %>
<%= "<OPTION VALUE='CN'>CN" %>