<SCRIPT LANGUAGE="JavaScript" FOR="VendorBtnControl" EVENT="onscriptletevent (event, obj)">
   switch (event)
	{
	case "EDITBUTTONCLICK":
 		window.location.href = "../Vendor/VendorDetail.asp?VENDORID=1";
		break;

	case "NEWBUTTONCLICK":
		window.location.href = "about:blank";
		break;

	case "COPYBUTTONCLICK":
		window.location.href = "about:blank";
		break;

	case "PASTEBUTTONCLICK":
		window.location.href = "about:blank";
		break;

	case "SEARCHBUTTONCLICK":
		window.location.href = "about:blank";
		break;

	case "REMOVEBUTTONCLICK":
		window.location.href = "about:blank";
		break;

		default:
		break;
	}
   
</SCRIPT>