<!--#include file="..\lib\common.inc"-->
<!--#include file="..\lib\RenderTextInc.asp"-->
<%

Function AddSpace(Num)
For i = 1 to Num Step 1
	Response.Write("&nbsp;")
Next
End Function 

If Len(Request.QueryString("FRAMEID")) < 1 OR IsNumeric(Request.QueryString("FRAMEID")) = False Then
	Session("ErrorMessage") = "On page " &  Request.ServerVariables("SCRIPT_NAME") & " QueryString FRAMEID was Null or Not Numeric"
	Response.Redirect "..\directerror.asp"
End If
	Set Conn = Server.CreateObject("ADODB.Connection")
	ConnectionString = CONNECT_STRING
	Conn.Open ConnectionString
	
	
	SQLST = ""
	SQLST = SQLST & "SELECT ATTR_INSTANCE.ATTR_INSTANCE_ID, ATTR_INSTANCE.TYPE, ATTR_INSTANCE.SEQUENCE, ATTR_INSTANCE.XPOS, ATTR_INSTANCE.YPOS, "
	SQLST = SQLST & "ATTR_INSTANCE.WIDTH, ATTR_INSTANCE.HEIGHT, ATTR_INSTANCE.MANDATORY_FLG, "
	SQLST = SQLST & "ATTR_INSTANCE.CAPTION, ATTR_INSTANCE.INPUTTYPE, ATTR_INSTANCE.ENTRYMASK, ATTR_INSTANCE.VALIDVALUEFIELD_FLG, "
	SQLST = SQLST & "ATTR_INSTANCE.DEFAULTVALUE, ATTR_INSTANCE.UNKNOWNVALUE, ATTR_INSTANCE.TEXTLENGTH, ATTR_INSTANCE.VISIBLERULE_ID, "
	SQLST = SQLST & "ATTR_INSTANCE.ENABLEDRULE_ID, ATTR_INSTANCE.VALIDRULE_ID, ATTR_INSTANCE.PERSISTRULE_ID, ATTR_INSTANCE.ACTION_ID, "
	SQLST = SQLST & "ATTR_INSTANCE.ATTRIBUTEFRAME_ID, ATTR_INSTANCE.SPELLCHECK_FLG,ATTR_INSTANCE.REAPPLYOVERRIDE_FLG, ATTR_INSTANCE.HELPSTRING, ATTR_INSTANCE.DESCRIPTION, "
	SQLST = SQLST & "ATTRIBUTE.NAME As AT_NAME, ATTRIBUTE.CAPTION As AT_CAPTION, ATTRIBUTE.INPUTTYPE As AT_INPUTTYPE, ATTRIBUTE.ENTRYMASK As AT_ENTRYMASK, "
	SQLST = SQLST & "ATTRIBUTE.VALIDVALUEFIELD_FLG As AT_VALIDVALUEFIELD_FLG, ATTRIBUTE.DEFAULTVALUE As AT_DEFAULTVALUE, "
	SQLST = SQLST & "ATTRIBUTE.UNKNOWNVALUE As AT_UNKNOWNVALUE, ATTRIBUTE.TEXTLENGTH As AT_TEXTLENGTH, ATTRIBUTE.VISIBLERULE_ID As AT_VISIBLERULE_ID, "
	SQLST = SQLST & "ATTRIBUTE.ENABLEDRULE_ID As AT_ENABLEDRULE_ID, ATTRIBUTE.VALIDRULE_ID As AT_VALIDRULE_ID, "
	SQLST = SQLST & "ATTRIBUTE.ATTRIBUTE_ID, ATTRIBUTE.PERSISTRULE_ID As AT_PERSISTRULE_ID, ATTRIBUTE.ACTION_ID As AT_ACTION_ID, ATTRIBUTE.SPELLCHECK_FLG As AT_SPELLCHECK_FLG, "
	SQLST = SQLST & "ATTRIBUTE.HELPSTRING As AT_HELPSTRING, ATTRIBUTE.DESCRIPTION As AT_DESCRIPTION "
	SQLST = SQLST & "FROM ATTR_INSTANCE, 	ATTRIBUTE WHERE "
	SQLST = SQLST & "ATTR_INSTANCE.ATTRIBUTE_ID = ATTRIBUTE.ATTRIBUTE_ID AND "
	SQLST = SQLST & "ATTR_INSTANCE.FRAME_ID = " & Request.QueryString("FRAMEID") & " Order By ATTR_INSTANCE.SEQUENCE"
	Set RS = Conn.Execute(SQLST)
	
%>
<HTML>
<link rel="stylesheet" type="text/css" href="..\FNSDESIGN.css">
<HEAD>
<META name=VI60_defaultClientScript content=VBScript>
<SCRIPT ID=clientEventHandlersVBS LANGUAGE=vbscript>
<!--
Sub ShowDetails(ID, SPANID)
If ID.style.display = "block" = true Then
	ID.style.display = "none"
	SPANID.innerhtml = " + "
Else
	ID.style.display = "block"
	SPANID.innerhtml = " - "
End If
End Sub


Sub EXPANDALL_onclick
	self.location.href = "CF_Attrib_List.asp?EXPAND=TRUE&<%= Request.QueryString %>"
End Sub

-->
</SCRIPT>
</HEAD>
<BODY BGCOLOR="#d6cfbd">
<TABLE WIDTH="100%" CELLPADDING="0" CELLSPACING="0">
<TR><TD colspan=2 HEIGHT=4></TD></TR>
<TR><TD CLASS=GrpLabel WIDTH="134" HEIGHT=10><NOBR>&nbsp&#187 Attribute Instance Listing &nbsp;&nbsp; <SPAN ID=EXPANDALL CLASS=LABEL STYLE='CURSOR:HAND'  title="Expand All"><FONT COLOR="WHITE"><B>+</B></FONT></SPAN></TD>
<TD HEIGHT=5 ALIGN=LEFT>
<TABLE CELLPADDING="0" CELLSPACING="0" HEIGHT=100%>
<TR><TD WIDTH=3 HEIGHT=4></TD><TD WIDTH=300 HEIGHT=4></TD></TR>
<TR><TD CLASS=GrpLabelDrk WIDTH=3 HEIGHT=8 VALIGN=BOTTOM ALIGN=LEFT></TD>
<TD WIDTH=300 HEIGHT=8></TD></TR>
</TABLE></TD></TR>
<TR><TD CLASS=GrpLabelLine colspan=2 HEIGHT=1></TD></TR>
<TR><TD colspan=2 HEIGHT=1></TD></TR>
</TABLE>
<TABLE WIDTH="100%" CELLSPACING=0 CELLPADDING=5 NAME=tbList ID=tbList>
<TR>
<TD CLASS=LABELLIST WIDTH=8></TD>
<TD CLASS=LABELLIST WIDTH="30%" NOWRAP>Instance Name</TD>
<TD CLASS=LABELLIST WIDTH=100 NOWRAP>Sequence</TD>
<TD CLASS=LABELLIST WIDTH=100 NOWRAP>Type</TD>
<TD CLASS=LABELLIST WIDTH=100 NOWRAP>Mandatory</TD>
<TD CLASS=LABELLIST WIDTH=100 NOWRAP>Width</TD>
<TD CLASS=LABELLIST WIDTH=100 NOWRAP>Height</TD>
</TR>
</TABLE>
<% Do WHile Not RS.EOF %>
<TABLE>
<TR STYLE="CURSOR:HAND" onclick="ShowDetails <%= "ID" & Replace(RS("ATTR_INSTANCE_ID"), "-", "") %>,<%= "PLUS" & Replace(RS("ATTR_INSTANCE_ID"), "-", "") %>">
<TD CLASS=LABELDATA><SPAN ID="<%= "PLUS" & Replace(RS("ATTR_INSTANCE_ID"), "-", "") %>" NAME="<%= "PLUS" & Replace(RS("ATTR_INSTANCE_ID"), "-", "") %>"> + </SPAN></TD>
<TD CLASS=LABELDATA WIDTH="38%" NOWRAP><%= RS("AT_NAME") %></TD>
<TD CLASS=LABELDATA WIDTH=100 NOWRAP><%= RS("SEQUENCE") %></TD>
<TD CLASS=LABELDATA WIDTH=100 NOWRAP><%= RS("TYPE") %></TD>
<TD CLASS=LABELDATA WIDTH=100 NOWRAP><%= RS("MANDATORY_FLG") %></TD>
<TD CLASS=LABELDATA WIDTH=100 NOWRAP><%= RS("WIDTH") %></TD>
<TD CLASS=LABELDATA WIDTH=100 NOWRAP><%= RS("HEIGHT") %></TD>
</TR>
</TABLE>
<SPAN ID="<%= "ID" & Replace(RS("ATTR_INSTANCE_ID"), "-", "")  %>" 	onclick="ShowDetails <%= "ID" & Replace(RS("ATTR_INSTANCE_ID"), "-", "")  %>,<%= "PLUS" & Replace(RS("ATTR_INSTANCE_ID"), "-", "") %>" 
<% If Request.QueryString("EXPAND") = "TRUE" Then %>
STYLE="DISPLAY:BLOCK;CURSOR:HAND;"
<% Else %>
STYLE="DISPLAY:NONE;CURSOR:HAND;"
<% End If %>
>
<TABLE WIDTH=100%>
<TR>
<TD CLASS=LABELDATA WIDTH=400><FONT SIZE=1><B>INSTANCE VALUES</B></FONT></TD>
<TD CLASS=LABELDATA><FONT SIZE=1><B>ATTRIBUTE VALUES</B></FONT></TD>
</TR>
<TR>
<TD CLASS=LABELDATA WIDTH=400><NOBR>INSTANCE_ID=<%=RS("ATTR_INSTANCE_ID") %></TD>
<TD CLASS=LABELDATA><NOBR>ATTRIBUTE_ID = <%= RS("ATTRIBUTE_ID") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA WIDTH=400><NOBR>CAPTION=<%= RS("CAPTION") %></TD>
<TD CLASS=LABELDATA><NOBR>CAPTION = <%= RS("AT_CAPTION") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA WIDTH=400><NOBR>INPUT TYPE = <%= RS("INPUTTYPE") %></TD>
<TD CLASS=LABELDATA><NOBR>INPUT TYPE = <%= RS("AT_INPUTTYPE") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA WIDTH=400><NOBR>ENTRY MASK = <%= RS("ENTRYMASK") %></TD>
<TD CLASS=LABELDATA><NOBR>ENTRY MASK = <%= RS("AT_ENTRYMASK") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>DEFAULT VALUE = <%= RS("DEFAULTVALUE") %></TD>
<TD CLASS=LABELDATA><NOBR>DEFAULT VALUE = <%= RS("AT_DEFAULTVALUE") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>UNKNOWN VALUE = <%= RS("UNKNOWNVALUE") %></TD>
<TD CLASS=LABELDATA><NOBR>UNKNOWN VALUE = <%= RS("AT_UNKNOWNVALUE") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>HELPSTRING = <%= TruncateText(RS("HELPSTRING"), 40) %></TD>
<TD CLASS=LABELDATA><NOBR>HELPSTRING = <%= TruncateText(RS("AT_HELPSTRING"), 40) %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>TEXTLENGTH = <%= RS("TEXTLENGTH") %></TD>
<TD CLASS=LABELDATA><NOBR>TEXTLENGTH = <%= RS("AT_TEXTLENGTH") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>VALIDVALUEFIELD_FLG = <%= RS("VALIDVALUEFIELD_FLG") %></TD>
<TD CLASS=LABELDATA><NOBR>VALIDVALUEFIELD_FLG = <%= RS("AT_VALIDVALUEFIELD_FLG") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>VALIDRULE_ID = <%= RS("VALIDRULE_ID") %></TD>
<TD CLASS=LABELDATA><NOBR>VALIDRULE_ID = <%= RS("AT_VALIDRULE_ID") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>VISIBLERULE_ID = <%= RS("VISIBLERULE_ID") %></TD>
<TD CLASS=LABELDATA><NOBR>VISIBLERULE_ID = <%= RS("AT_VISIBLERULE_ID") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>ENABLEDRULE_ID = <%= RS("ENABLEDRULE_ID") %></TD>
<TD CLASS=LABELDATA><NOBR>ENABLEDRULE_ID = <%= RS("AT_ENABLEDRULE_ID") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>PERSISTRULE_ID = <%= RS("PERSISTRULE_ID") %></TD>
<TD CLASS=LABELDATA><NOBR>PERSISTRULE_ID = <%= RS("AT_PERSISTRULE_ID") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>ACTION_ID = <%= RS("ACTION_ID") %></TD>
<TD CLASS=LABELDATA><NOBR>ACTION_ID = <%= RS("AT_ACTION_ID") %></TD>
</TR>
<TR>
<TD CLASS=LABELDATA><NOBR>ATTRIBUTEFRAME ID = <%= RS("ATTRIBUTEFRAME_ID") %></TD>
<TD CLASS=LABELDATA>N/A</TD>
</TR>

</TABLE>
</SPAN>
<TABLE WIDTH="100%">
<TR><TD CLASS=GrpLabelLine colspan=12 HEIGHT=1></TD></TR>
<TR><TD colspan=12 HEIGHT=1></TD></TR>
</TABLE>

<% 
RS.MoveNext
loop
RS.close
%>
</BODY>
</HTML>
