<!--#include file="..\lib\common.inc"-->
<HTML>
<HEAD>
<link rel="stylesheet" type="text/css" href="..\FNSDESIGN.css">
</HEAD>
<BODY BGCOLOR=#d6cfbd topmargin=0 leftmargin=0>

<TABLE WIDTH=100% CELLPADDING="0" CELLSPACING="0">
<TR><TD colspan=2 HEIGHT=4></TD></TR>
<TR><TD CLASS=GrpLabel WIDTH="134" HEIGHT=10>&nbsp&#187 Exit Validation Rule
</TD>
<TD HEIGHT=5 ALIGN=LEFT>
<TABLE CELLPADDING="0" CELLSPACING="0" HEIGHT=100%>
<TR><TD WIDTH=3 HEIGHT=4></TD><TD WIDTH=300 HEIGHT=4></TD></TR>
<TR><TD CLASS=GrpLabelDrk WIDTH=3 HEIGHT=8 VALIGN=BOTTOM ALIGN=LEFT></TD>
<TD WIDTH=300 HEIGHT=8></TD></TR>
</TABLE></TD></TR>
<TR><TD CLASS=GrpLabelLine colspan=2 HEIGHT=1></TD></TR>
<TR><TD colspan=2 HEIGHT=1></TD></TR>
</TABLE>



<FIELDSET STYLE="WIDTH:300">
<LEGEND CLASS=LABEL>Attribute</LEGEND>
<TABLE>
<TR>
<TD CLASS=LABEL>
<SELECT NAME="ATTR1" CLASS=LABEL STYLE="WIDTH:125">
<OPTION>Caller:
<OPTION>Injured:
<OPTION>Damaged:
</SELECT>
</TD>
<TD CLASS=LABEL>
<SELECT NAME="ATTR1" CLASS=LABEL STYLE="WIDTH:125">
<OPTION>Address1:
<OPTION>Address2:
<OPTION>Damaged:
</SELECT>
</TD>
<TD CLASS=LABEL>
<BUTTON CLASS=STDBUTTON id=button1 name=button1>Full Search</BUTTON>
</TD>
<TD CLASS=LABEL>
<BUTTON CLASS=STDBUTTON STYLE="WIDTH:50" id=button2 name=button2>Enter</BUTTON>
</TD>
</TR>
</TABLE>
</FIELDSET>


<TABLE>
<TR>
<TD>
<FIELDSET WIDTH=200>
<LEGEND CLASS=LABEL>Operator</LEGEND>
<TABLE>
<TR>
<TD CLASS=LABEL>
<SELECT NAME="OPERATOR" CLASS=LABEL>
<OPTION>AND
<OPTION>OR
<OPTION>LESS THAN
<OPTION>LESS THAN OR EQUAL TO
<OPTION>GREATER THAN
<OPTION>GREATER THAN OR EQUAL TO
</SELECT>
</TD>
<TD CLASS=LABEL>
<BUTTON CLASS=STDBUTTON STYLE="WIDTH:50"  id=button3 name=button3>Enter</BUTTON>
</TD>
</TABLE>
</FIELDSET>
</TD>
<TD>
<FIELDSET>
<LEGEND CLASS=LABEL>Value</LEGEND>
<TABLE>
<TR>
<TD CLASS=LABEL><INPUT TYPE=TEXT SIZE=20 id=TEXT1 name=TEXT1></TD>
<TD CLASS=LABEL>
<BUTTON CLASS=STDBUTTON STYLE="WIDTH:50" id=button4 name=button4>Enter</BUTTON>
</TD>
</TR>
</TABLE>
</FIELDSET>
</TD>
</TR>
</TABLE>

<FIELDSET STYLE="WIDTH:300">
<LEGEND CLASS=LABEL>Expression Buffer</LEGEND>
<TABLE>
<TR>
<TD CLASS=LABEL><INPUT TYPE=TEXT SIZE=80 id=TEXT2 name=TEXT2></TD>
<TD CLASS=LABEL><BUTTON CLASS=STDBUTTON STYLE="WIDTH:50" id=button5 name=button5>Enter</BUTTON>
</TR>
</TABLE>
</FIELDSET>
<BR>
<LABEL CLASS=LABEL>Exit Rule:<BR></LABEL>
<TEXTAREA STYLE="WIDTH:600;HEIGHT:150" id=textarea1 name=textarea1></TEXTAREA><BR><BR>
<BUTTON CLASS=STDBUTTON id=button6 name=button6>To Buffer</BUTTON>&nbsp;
<BUTTON CLASS=STDBUTTON id=button7 name=button7>Clear</BUTTON>
</BODY>
</HTML>
